name: flutter_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.3.0

dependencies:
  http: ^1.1.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  provider: ^6.1.2
  # flutter_riverpod: ^3.0.3
  supabase_flutter: ^2.5.6
  image_picker: ^1.0.7
  file_picker: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  provider: ^6.0.5

flutter:
  uses-material-design: true
  assets:
    - assets/images/
